-- MySQL Script generated by MySQL Workbench
-- Mon Feb 19 17:32:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema appointments
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema appointments
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appointments` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `appointments` ;

-- -----------------------------------------------------
-- Table `appointments`.`clinics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appointments`.`clinics` (
  `clinicid` VARCHAR(45) NOT NULL,
  `hospitalname` LONGTEXT NULL DEFAULT NULL,
  `IsHospital` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `Province` VARCHAR(45) NULL DEFAULT NULL,
  `RegionName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`clinicid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appointments`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appointments`.`doctors` (
  `doctorid` VARCHAR(45) NOT NULL,
  `mainspecialty` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  PRIMARY KEY (`doctorid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appointments`.`px`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appointments`.`px` (
  `pxid` VARCHAR(45) NOT NULL,
  `age` INT NULL DEFAULT NULL,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`pxid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appointments`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appointments`.`appointments` (
  `pxid` VARCHAR(45) NULL DEFAULT NULL,
  `clinicid` VARCHAR(45) NULL DEFAULT NULL,
  `doctorid` VARCHAR(45) NULL DEFAULT NULL,
  `apptid` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `TimeQueued` DATETIME NULL DEFAULT NULL,
  `QueueDate` DATETIME NULL DEFAULT NULL,
  `StartTime` DATETIME NULL DEFAULT NULL,
  `EndTime` DATETIME NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `Virtual` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`apptid`),
  INDEX `pxid_idx` (`pxid` ASC) VISIBLE,
  INDEX `clinicid_idx` (`clinicid` ASC) VISIBLE,
  INDEX `doctorid_idx` (`doctorid` ASC) VISIBLE,
  CONSTRAINT `clinicid`
    FOREIGN KEY (`clinicid`)
    REFERENCES `appointments`.`clinics` (`clinicid`),
  CONSTRAINT `doctorid`
    FOREIGN KEY (`doctorid`)
    REFERENCES `appointments`.`doctors` (`doctorid`),
  CONSTRAINT `pxid`
    FOREIGN KEY (`pxid`)
    REFERENCES `appointments`.`px` (`pxid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
